Check for nf rate limiting (#730)
* check for nf rate limiting

* run name needs to be precomputed

* fix branch usage

* fix outputs syntax

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -335,7 +335,7 @@ jobs:
       with:
           name: coverage
 
-  run_benchmark:
+  setup_benchmark:
     needs:
     - run_tester
     - build_images
@@ -349,6 +349,10 @@ jobs:
         needs.run_tester.result == 'success' ||
         needs.run_tester.result == 'skipped'
       )
+
+    outputs:
+      branch: ${{ steps.setup-environment.outputs.branch }}
+      run_name: ${{ steps.setup-environment.outputs.run_name }}
 
     steps:
     - name: Check dependabot
@@ -407,6 +411,7 @@ jobs:
         wait
 
     - name: Set up environment
+      id: setup-environment
       run: |
         # If not on the base repository, append first 6 characters of username to the image name
         # to avoid clashes on ECR
@@ -421,6 +426,9 @@ jobs:
         fi
         BRANCH=`echo $BRANCH | sed 's/[^a-zA-Z0-9]*$//'`
         echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
+        echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
+        RUN_NAME="$(echo "$BRANCH" | sed "s/[^a-zA-Z0-9]/_/g")_$(git rev-parse --short HEAD)_${GITHUB_RUN_ATTEMPT}"
+        echo "run_name=${RUN_NAME}" >> $GITHUB_OUTPUT
 
     - name: Upload Docker images
       env:
@@ -437,35 +445,48 @@ jobs:
         done
         wait
 
+  run_benchmark:
+    needs:
+    - setup_benchmark
+    runs-on: ubuntu-latest
+    if: >-
+      always() &&
+      needs.setup_benchmark.result == 'success'
+
+    steps:
     - name: Run benchmark
       env:
         TOWER_WATCH_URL: https://tower.nf/orgs/openproblems-bio/workspaces/openproblems-bio/watch
         TOWER_WORKSPACE_ID: 53907369739130
+        BRANCH: ${{ needs.setup_benchmark.outputs.branch }}
       run: |
-        RUN_NAME="$(echo "$BRANCH" | sed "s/[^a-zA-Z0-9]/_/g")_$(git rev-parse --short HEAD)_${GITHUB_RUN_ATTEMPT}"
         if [[ ${{ startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/test_full_benchmark') }} == true ]]; then
           TOWER_ACTION_ID="bVQhVSNah1JmJfnKkfyjg"
           WORKDIR="s3://openproblems-nextflow/work_main"
         else
           TOWER_ACTION_ID="5BQc88ZvjuXCYbc55Hot27"
-          WORKDIR="s3://openproblems-nextflow/work/$BRANCH"
+          WORKDIR="s3://openproblems-nextflow/work/${BRANCH}"
         fi
         generate_parameters()
         {
         cat <<EOF
           {
             "params" : {
-              "branch": "$BRANCH"
+              "branch": "${BRANCH}"
             }
           }
         EOF
         }
-        WORKFLOW_ID=$(
+        OUTPUT=$(
             curl -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${{ secrets.TOWER_ACCESS_KEY }}" \
             https://api.tower.nf/actions/${TOWER_ACTION_ID}/launch?workspaceId=${TOWER_WORKSPACE_ID} \
-            --data "$(generate_parameters)" | \
-            tee /dev/stderr | \
-            sed 's/.*"\([a-zA-Z0-9]*\)".*/\1/'
+            --data "$(generate_parameters)"
         )
+        echo "$OUTPUT"
+        if [ $(echo "$OUTPUT" | grep "No more than 5 workflow runs at time are allowed") ]; then
+          echo "Nextflow Tower is currently rate limited. Please wait until fewer jobs are running and then retry failed jobs."
+          exit 1
+        fi
+        WORKFLOW_ID=$(echo "$OUTPUT" | sed 's/.*"\([a-zA-Z0-9]*\)".*/\1/')
         echo "Benchmark running at ${TOWER_WATCH_URL}/${WORKFLOW_ID}" >> $GITHUB_STEP_SUMMARY
