fix tower auth check

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -247,20 +247,24 @@ jobs:
         TOWER_WORKSPACE_ID: 53907369739130
       run: |
         result=$(
+          curl -X GET "https://api.tower.nf/user-info" \
+          -H "Accept: application/json" \
+          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
+        )
+        if [ -z "${result}" ]; then
+          echo "Tower authentication failed; set TOWER_ACCESS_KEY in repo secrets."
+          echo "See CONTRIBUTING.md for details."
+          exit 1
+        fi
+        result=$(
           curl -X GET "https://api.tower.nf/orgs/${TOWER_ORG_ID}/workspaces/${TOWER_WORKSPACE_ID}" \
           -H "Accept: application/json" \
-          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}" || \
-          (
-            echo "Tower authentication failed; set TOWER_ACCESS_KEY in repo secrets." >&2 &&
-            echo "See CONTRIBUTING.md for details." >&2 && \
-            exit 1
-          )
+          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
         )
         if [ -z "${result}" ]; then
           echo "Tower authentication failed; email singlecellopenproblems@protonmail.com with a request to be added to the openproblems-bio workspace"
           exit 1
         fi
-      shell: /bin/bash -e {0}
 
     - name: Set up Python
       uses: actions/setup-python@v4
