setup env still

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -232,44 +232,44 @@ jobs:
           echo "Dependabot cannot access Action secrets. Rerun the workflow manually"
           exit 1
         fi
-
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 1000
-
-    - name: Clear space on runner
-      run: ./scripts/clear_runner_diskspace.sh
+#
+#    - uses: actions/checkout@v3
+#      with:
+#        fetch-depth: 1000
+#
+#    - name: Clear space on runner
+#      run: ./scripts/clear_runner_diskspace.sh
 #
 #    - name: Install system dependencies
 #      run: |
 #        sudo apt-get update -qq || (sudo rm /etc/apt/sources.list.d/* && sudo apt-get update -yqq)
 #        sudo apt-get install -qy --no-install-recommends libhdf5-dev pandoc gfortran libblas-dev liblapack-dev libedit-dev llvm-dev
 #
-#    - name: Check Tower authentication
-#      env:
-#        TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_KEY }}
-#        TOWER_ORG_ID: 9180144064527
-#        TOWER_WORKSPACE_ID: 53907369739130
-#      run: |
-#        token_confirmation=$(
-#          curl -X GET "https://api.tower.nf/user-info" \
-#          -H "Accept: application/json" \
-#          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
-#        )
-#        if [ -z "${token_confirmation}" ]; then
-#          echo "Tower authentication failed; set TOWER_ACCESS_KEY in repo secrets."
-#          echo "See CONTRIBUTING.md for details."
-#          exit 1
-#        fi
-#        workspace_confirmation=$(
-#          curl -X GET "https://api.tower.nf/orgs/${TOWER_ORG_ID}/workspaces/${TOWER_WORKSPACE_ID}" \
-#          -H "Accept: application/json" \
-#          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
-#        )
-#        if [ -z "${workspace_confirmation}" ]; then
-#          echo "Tower authentication failed; email singlecellopenproblems@protonmail.com with a request to be added to the openproblems-bio workspace"
-#          exit 1
-#        fi
+    - name: Check Tower authentication
+      env:
+        TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_KEY }}
+        TOWER_ORG_ID: 9180144064527
+        TOWER_WORKSPACE_ID: 53907369739130
+      run: |
+        token_confirmation=$(
+          curl -X GET "https://api.tower.nf/user-info" \
+          -H "Accept: application/json" \
+          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
+        )
+        if [ -z "${token_confirmation}" ]; then
+          echo "Tower authentication failed; set TOWER_ACCESS_KEY in repo secrets."
+          echo "See CONTRIBUTING.md for details."
+          exit 1
+        fi
+        workspace_confirmation=$(
+          curl -X GET "https://api.tower.nf/orgs/${TOWER_ORG_ID}/workspaces/${TOWER_WORKSPACE_ID}" \
+          -H "Accept: application/json" \
+          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
+        )
+        if [ -z "${workspace_confirmation}" ]; then
+          echo "Tower authentication failed; email singlecellopenproblems@protonmail.com with a request to be added to the openproblems-bio workspace"
+          exit 1
+        fi
 #
 #    - name: Set up Python
 #      uses: actions/setup-python@v4
@@ -283,26 +283,26 @@ jobs:
 #        architecture: x64
 #        distribution: zulu
 #
-#    - name: Set up environment
-#      run: |
-#        SCRIPTS_PATH=$(python3 -c 'import os, sysconfig; print(sysconfig.get_path("scripts",f"{os.name}_user"))')
-#        echo "PATH=${SCRIPTS_PATH}:${PATH}" >> $GITHUB_ENV
-#        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
-#        echo "PYTHON_LOCATION=$(which python3)" >> $GITHUB_ENV
-#        echo "UBUNTU_VERSION=`grep DISTRIB_RELEASE /etc/lsb-release | sed 's/.*=//g'`" >> $GITHUB_ENV
-#        # If not on the base repository, append first 6 characters of username to the image name
-#        # to avoid clashes on ECR
-#        REPO_PARSED=$(echo ${{ github.repository }} | awk '{print $1}' FS=/ | head -c 6)
-#        BRANCH_PARSED=$(echo ${{ github.ref }} | sed 's:refs/[a-z]*/::' | sed 's:[^a-zA-Z0-9]:-:g')
-#        if [[ ${{ startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/test_full_benchmark') }} == true ]]; then
-#          BRANCH="prod"
-#        elif [[ "${{ github.repository }}" == "openproblems-bio/openproblems" ]]; then
-#          BRANCH=`echo $BRANCH_PARSED | head -c 40`
-#        else
-#          BRANCH="${REPO_PARSED}-`echo $BRANCH_PARSED | head -c 33`"
-#        fi
-#        BRANCH=`echo $BRANCH | sed 's/[^a-zA-Z0-9]*$//'`
-#        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
+    - name: Set up environment
+      run: |
+        SCRIPTS_PATH=$(python3 -c 'import os, sysconfig; print(sysconfig.get_path("scripts",f"{os.name}_user"))')
+        echo "PATH=${SCRIPTS_PATH}:${PATH}" >> $GITHUB_ENV
+        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
+        echo "PYTHON_LOCATION=$(which python3)" >> $GITHUB_ENV
+        echo "UBUNTU_VERSION=`grep DISTRIB_RELEASE /etc/lsb-release | sed 's/.*=//g'`" >> $GITHUB_ENV
+        # If not on the base repository, append first 6 characters of username to the image name
+        # to avoid clashes on ECR
+        REPO_PARSED=$(echo ${{ github.repository }} | awk '{print $1}' FS=/ | head -c 6)
+        BRANCH_PARSED=$(echo ${{ github.ref }} | sed 's:refs/[a-z]*/::' | sed 's:[^a-zA-Z0-9]:-:g')
+        if [[ ${{ startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/test_full_benchmark') }} == true ]]; then
+          BRANCH="prod"
+        elif [[ "${{ github.repository }}" == "openproblems-bio/openproblems" ]]; then
+          BRANCH=`echo $BRANCH_PARSED | head -c 40`
+        else
+          BRANCH="${REPO_PARSED}-`echo $BRANCH_PARSED | head -c 33`"
+        fi
+        BRANCH=`echo $BRANCH | sed 's/[^a-zA-Z0-9]*$//'`
+        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
 #
 #    - name: Cache Python packages
 #      uses: actions/cache@v3
