set sessionId

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -239,158 +239,158 @@ jobs:
 
     - name: Clear space on runner
       run: ./scripts/clear_runner_diskspace.sh
-
-    - name: Install system dependencies
-      run: |
-        sudo apt-get update -qq || (sudo rm /etc/apt/sources.list.d/* && sudo apt-get update -yqq)
-        sudo apt-get install -qy --no-install-recommends libhdf5-dev pandoc gfortran libblas-dev liblapack-dev libedit-dev llvm-dev
-
-    - name: Check Tower authentication
-      env:
-        TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_KEY }}
-        TOWER_ORG_ID: 9180144064527
-        TOWER_WORKSPACE_ID: 53907369739130
-      run: |
-        token_confirmation=$(
-          curl -X GET "https://api.tower.nf/user-info" \
-          -H "Accept: application/json" \
-          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
-        )
-        if [ -z "${token_confirmation}" ]; then
-          echo "Tower authentication failed; set TOWER_ACCESS_KEY in repo secrets."
-          echo "See CONTRIBUTING.md for details."
-          exit 1
-        fi
-        workspace_confirmation=$(
-          curl -X GET "https://api.tower.nf/orgs/${TOWER_ORG_ID}/workspaces/${TOWER_WORKSPACE_ID}" \
-          -H "Accept: application/json" \
-          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
-        )
-        if [ -z "${workspace_confirmation}" ]; then
-          echo "Tower authentication failed; email singlecellopenproblems@protonmail.com with a request to be added to the openproblems-bio workspace"
-          exit 1
-        fi
-
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: "3.8"
-
-    - name: Set up Java ${{ matrix.java_version }}
-      uses: actions/setup-java@v3
-      with:
-        java-version: 15
-        architecture: x64
-        distribution: zulu
-
-    - name: Set up environment
-      run: |
-        SCRIPTS_PATH=$(python3 -c 'import os, sysconfig; print(sysconfig.get_path("scripts",f"{os.name}_user"))')
-        echo "PATH=${SCRIPTS_PATH}:${PATH}" >> $GITHUB_ENV
-        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
-        echo "PYTHON_LOCATION=$(which python3)" >> $GITHUB_ENV
-        echo "UBUNTU_VERSION=`grep DISTRIB_RELEASE /etc/lsb-release | sed 's/.*=//g'`" >> $GITHUB_ENV
-        # If not on the base repository, append first 6 characters of username to the image name
-        # to avoid clashes on ECR
-        REPO_PARSED=$(echo ${{ github.repository }} | awk '{print $1}' FS=/ | head -c 6)
-        BRANCH_PARSED=$(echo ${{ github.ref }} | sed 's:refs/[a-z]*/::' | sed 's:[^a-zA-Z0-9]:-:g')
-        if [[ ${{ startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/test_full_benchmark') }} == true ]]; then
-          BRANCH="prod"
-        elif [[ "${{ github.repository }}" == "openproblems-bio/openproblems" ]]; then
-          BRANCH=`echo $BRANCH_PARSED | head -c 40`
-        else
-          BRANCH="${REPO_PARSED}-`echo $BRANCH_PARSED | head -c 33`"
-        fi
-        BRANCH=`echo $BRANCH | sed 's/[^a-zA-Z0-9]*$//'`
-        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
-
-    - name: Cache Python packages
-      uses: actions/cache@v3
-      with:
-        path: ${{ env.pythonLocation }}
-        key: ${{ env.UBUNTU_VERSION }}-pip-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
-        restore-keys: ${{ env.UBUNTU_VERSION}}-pip-${{ env.pythonLocation }}-
-
-    - name: Install Nextflow
-      env:
-          CAPSULE_LOG: none
-          NXF_VER: 22.10.2
-      run: |
-        mkdir /tmp/nextflow
-        cd /tmp/nextflow
-        wget -qO- get.nextflow.io | bash
-        sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
-        nextflow -version
-
-    - name: Install AWS CLI
-      run: |
-        mkdir /tmp/awscli
-        cd /tmp/awscli
-        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-        unzip -q awscliv2.zip
-        sudo ./aws/install || sudo ./aws/install --update
-        aws --version
-
-    - name: Set up S3FS
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: us-west-2
-      run: |
-        sudo apt-get install -qy --no-install-recommends s3fs
-        echo $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY > ~/.passwd-s3fs
-        chmod 600 ~/.passwd-s3fs
-        sudo mkdir -p /mnt/openproblems-nextflow
-        sudo chown $USER /mnt/openproblems-nextflow
-        s3fs -o umask=0277,uid=$(id -u) openproblems-nextflow /mnt/openproblems-nextflow
-        # Create bucket/ work/ and cwd/
-        for dir in bucket work cwd; do
-          mkdir -p /mnt/openproblems-nextflow/${dir}/${BRANCH}
-        done
-        ls -l /mnt/openproblems-nextflow/*/${BRANCH}
-
-    - name: Install package & dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -U wheel setuptools
-        pip install -U --editable .[evaluate,process]
-        python -c "import openproblems"
-        openproblems-cli --version
-        openproblems-cli --test-hash
-
-    - name: Pull Docker images
-      if: |
-        startsWith(github.ref, 'refs/heads/main') &&
-        github.repository == 'openproblems-bio/openproblems'
-      run: |
-        cd workflow
-        snakemake -j $(nproc) docker_pull
-        cd ..
-
-    - name: Build Docker images
-      if: |
-        !(
-          startsWith(github.ref, 'refs/heads/main') &&
-          github.repository == 'openproblems-bio/openproblems'
-        )
-      run: |
-        cd workflow
-        SNAKEMAKE_COPY_SOURCE=1 snakemake -j $(nproc) docker
-        cd ..
-
-    - name: Upload Docker images
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: us-west-2
-      run: |
-        ECR_ENDPOINT="490915662541.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
-        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | \
-          docker login --username AWS --password-stdin $ECR_ENDPOINT
-        for image in $(cd docker && ls -1d */ | tr -d '/'); do
-          docker tag singlecellopenproblems/${image} ${ECR_ENDPOINT}/openproblems:${BRANCH}-${image}
-          docker push --quiet ${ECR_ENDPOINT}/openproblems:${BRANCH}-${image}
-        done
+#
+#    - name: Install system dependencies
+#      run: |
+#        sudo apt-get update -qq || (sudo rm /etc/apt/sources.list.d/* && sudo apt-get update -yqq)
+#        sudo apt-get install -qy --no-install-recommends libhdf5-dev pandoc gfortran libblas-dev liblapack-dev libedit-dev llvm-dev
+#
+#    - name: Check Tower authentication
+#      env:
+#        TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_KEY }}
+#        TOWER_ORG_ID: 9180144064527
+#        TOWER_WORKSPACE_ID: 53907369739130
+#      run: |
+#        token_confirmation=$(
+#          curl -X GET "https://api.tower.nf/user-info" \
+#          -H "Accept: application/json" \
+#          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
+#        )
+#        if [ -z "${token_confirmation}" ]; then
+#          echo "Tower authentication failed; set TOWER_ACCESS_KEY in repo secrets."
+#          echo "See CONTRIBUTING.md for details."
+#          exit 1
+#        fi
+#        workspace_confirmation=$(
+#          curl -X GET "https://api.tower.nf/orgs/${TOWER_ORG_ID}/workspaces/${TOWER_WORKSPACE_ID}" \
+#          -H "Accept: application/json" \
+#          -H "Authorization: Bearer ${TOWER_ACCESS_TOKEN}"
+#        )
+#        if [ -z "${workspace_confirmation}" ]; then
+#          echo "Tower authentication failed; email singlecellopenproblems@protonmail.com with a request to be added to the openproblems-bio workspace"
+#          exit 1
+#        fi
+#
+#    - name: Set up Python
+#      uses: actions/setup-python@v4
+#      with:
+#        python-version: "3.8"
+#
+#    - name: Set up Java ${{ matrix.java_version }}
+#      uses: actions/setup-java@v3
+#      with:
+#        java-version: 15
+#        architecture: x64
+#        distribution: zulu
+#
+#    - name: Set up environment
+#      run: |
+#        SCRIPTS_PATH=$(python3 -c 'import os, sysconfig; print(sysconfig.get_path("scripts",f"{os.name}_user"))')
+#        echo "PATH=${SCRIPTS_PATH}:${PATH}" >> $GITHUB_ENV
+#        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
+#        echo "PYTHON_LOCATION=$(which python3)" >> $GITHUB_ENV
+#        echo "UBUNTU_VERSION=`grep DISTRIB_RELEASE /etc/lsb-release | sed 's/.*=//g'`" >> $GITHUB_ENV
+#        # If not on the base repository, append first 6 characters of username to the image name
+#        # to avoid clashes on ECR
+#        REPO_PARSED=$(echo ${{ github.repository }} | awk '{print $1}' FS=/ | head -c 6)
+#        BRANCH_PARSED=$(echo ${{ github.ref }} | sed 's:refs/[a-z]*/::' | sed 's:[^a-zA-Z0-9]:-:g')
+#        if [[ ${{ startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/test_full_benchmark') }} == true ]]; then
+#          BRANCH="prod"
+#        elif [[ "${{ github.repository }}" == "openproblems-bio/openproblems" ]]; then
+#          BRANCH=`echo $BRANCH_PARSED | head -c 40`
+#        else
+#          BRANCH="${REPO_PARSED}-`echo $BRANCH_PARSED | head -c 33`"
+#        fi
+#        BRANCH=`echo $BRANCH | sed 's/[^a-zA-Z0-9]*$//'`
+#        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
+#
+#    - name: Cache Python packages
+#      uses: actions/cache@v3
+#      with:
+#        path: ${{ env.pythonLocation }}
+#        key: ${{ env.UBUNTU_VERSION }}-pip-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
+#        restore-keys: ${{ env.UBUNTU_VERSION}}-pip-${{ env.pythonLocation }}-
+#
+#    - name: Install Nextflow
+#      env:
+#          CAPSULE_LOG: none
+#          NXF_VER: 22.10.2
+#      run: |
+#        mkdir /tmp/nextflow
+#        cd /tmp/nextflow
+#        wget -qO- get.nextflow.io | bash
+#        sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
+#        nextflow -version
+#
+#    - name: Install AWS CLI
+#      run: |
+#        mkdir /tmp/awscli
+#        cd /tmp/awscli
+#        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+#        unzip -q awscliv2.zip
+#        sudo ./aws/install || sudo ./aws/install --update
+#        aws --version
+#
+#    - name: Set up S3FS
+#      env:
+#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#        AWS_DEFAULT_REGION: us-west-2
+#      run: |
+#        sudo apt-get install -qy --no-install-recommends s3fs
+#        echo $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY > ~/.passwd-s3fs
+#        chmod 600 ~/.passwd-s3fs
+#        sudo mkdir -p /mnt/openproblems-nextflow
+#        sudo chown $USER /mnt/openproblems-nextflow
+#        s3fs -o umask=0277,uid=$(id -u) openproblems-nextflow /mnt/openproblems-nextflow
+#        # Create bucket/ work/ and cwd/
+#        for dir in bucket work cwd; do
+#          mkdir -p /mnt/openproblems-nextflow/${dir}/${BRANCH}
+#        done
+#        ls -l /mnt/openproblems-nextflow/*/${BRANCH}
+#
+#    - name: Install package & dependencies
+#      run: |
+#        python -m pip install --upgrade pip
+#        pip install -U wheel setuptools
+#        pip install -U --editable .[evaluate,process]
+#        python -c "import openproblems"
+#        openproblems-cli --version
+#        openproblems-cli --test-hash
+#
+#    - name: Pull Docker images
+#      if: |
+#        startsWith(github.ref, 'refs/heads/main') &&
+#        github.repository == 'openproblems-bio/openproblems'
+#      run: |
+#        cd workflow
+#        snakemake -j $(nproc) docker_pull
+#        cd ..
+#
+#    - name: Build Docker images
+#      if: |
+#        !(
+#          startsWith(github.ref, 'refs/heads/main') &&
+#          github.repository == 'openproblems-bio/openproblems'
+#        )
+#      run: |
+#        cd workflow
+#        SNAKEMAKE_COPY_SOURCE=1 snakemake -j $(nproc) docker
+#        cd ..
+#
+#    - name: Upload Docker images
+#      env:
+#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#        AWS_DEFAULT_REGION: us-west-2
+#      run: |
+#        ECR_ENDPOINT="490915662541.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
+#        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | \
+#          docker login --username AWS --password-stdin $ECR_ENDPOINT
+#        for image in $(cd docker && ls -1d */ | tr -d '/'); do
+#          docker tag singlecellopenproblems/${image} ${ECR_ENDPOINT}/openproblems:${BRANCH}-${image}
+#          docker push --quiet ${ECR_ENDPOINT}/openproblems:${BRANCH}-${image}
+#        done
 
     - name: Run benchmark
       env:
@@ -400,17 +400,21 @@ jobs:
         RUN_NAME="$(echo "$BRANCH" | sed "s/[^a-zA-Z0-9]/_/g")_$(git rev-parse --short HEAD)_${GITHUB_RUN_ATTEMPT}"
         if [[ ${{ startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/test_full_benchmark') }} == true ]]; then
           TOWER_ACTION_ID="bVQhVSNah1JmJfnKkfyjg"
+          WORKDIR="s3://openproblems-nextflow/work_main"
         else
           TOWER_ACTION_ID="5BQc88ZvjuXCYbc55Hot27"
+          WORKDIR="s3://openproblems-nextflow/work/$BRANCH"
         fi
         generate_parameters()
         {
         cat <<EOF
           {
             "params" : {
-              "branch": "$BRANCH",
-              "name": "$RUN_NAME"
-            }
+              "branch": "$BRANCH"
+            },
+            "workDir" : "$WORKDIR",
+            "resume" : true,
+            "sessionId" : "$RUN_NAME"
           }
         EOF
         }
